apiVersion: v1
kind: Secret
metadata:
  name: enterprise-secret
  namespace: enterprise-app

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SECRET_KEY: mysecretkey